name: Colab
datadir: '/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets'
num_nodes: 315
num_edges: 5104
timestamp: 10
features_dim: ${dataset.num_nodes}
num_classes: 2

dts: 
  link_pred:
    _target_: dgt.datasets.LinkPredData
    datadir: ${dataset.datadir}
    dataname: ${dataset.name}
    dgb: True
    evolving: ${model.evolving}
    score: ${model.score}
    n_nodes: ${dataset.num_nodes}
    one_hot: True
    sampling: ${task.sampling}
    train_ratio : ${task.train_ratio}
    split: ${task.split}
    k_test: 3
    k_val: 0
    pred_next : ${model.pred_next}